version: '2'
services:
  php:
    container_name: yii_php
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql
  mysql:
    container_name: yii_mysql
    image: mysql:5.7
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=yii_root
      - MYSQL_DATABASE=articles
      - MYSQL_CHARSET=utf8
      - MYSQL_COLLATION=utf8_general_ci
    command: [ "--default-authentication-plugin=mysql_native_password" ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
    mysql:

